name: ba_testing

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - black>=21
  - cookiecutter
  - dask
  - jupyterlab
  - munch
  - nodejs
  - pip
  - pytest
  - python=3.9
  - python-dotenv
  - pyarrow
  - pyyaml
  - swifter
  - tabulate
  - pip:
    - bump2version
    - ipykernel
    - nbsphinx
    - placekey
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx-copybutton
#    - tox
#    - tox-conda
#    - twine
