name: Make Docs

run-name: Make docs on branch - ${{ github.ref_name }}

# when any pushes are made to any branch with changes to the source, notebooks or docs directory
on:
  push:
    paths:
      - "src/**/*.py"
      - "notebooks/**/*.ipynb"
      - "docs/**"
      - ".github/workflows/**"

# set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    # run on linux since simpliest enviroment and no operating system dependencies are required
    runs-on: ubuntu-latest

    steps:

    # get the repo contents
    - uses: actions/checkout@v3

    # build the docs with a slightly tweaked custom command
    # - name: Build Sphinx Docs
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docsrc"
        build-command: "sphinx-build -a -b html . ../../docs"

    # ensure pages configured correctly
    - name: Setup Pages
      uses: actions/configure-pages@v2
      
    # upload docs directory
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload contents of docs directory
        path: "docs"
      
    # deploy automatically to GitHub pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1