name: Make Docs

run-name: Make Docs

# when any pushes are made to any branch with changes to the source, notebooks or docs directory
on:
  push:
    branches:
      - main
    paths:
      - "src/**/*.py"
      - "notebooks/**/*.ipynb"
      - "docs/**"
      - ".github/workflows/**"

# set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    # run on linux since simpliest enviroment and no operating system dependencies are required
    runs-on: ubuntu-latest

    steps:

    # get the repo contents
    - uses: actions/checkout@v3

    # install pandoc so nbsphinx will work
    - name: Install PanDoc
      run: "sudo apt-get install pandoc"

    # install miniconda so can install pandoc using conda
    - name: Install MiniConda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        chmod +x Miniconda3-latest-Linux-x86_64.sh
        sudo bash ./Miniconda3-latest-Linux-x86_64.sh -b

    # create and activate the conda environment
    - name: Create Conda Environment
      run: |
        conda create -n sphinx-build python=3.9
        conda activate sphinx-build

    # install python packages
    - name: Install Python Packages
      run: |
        conda install -c conda-forge pandoc ipython jinja2 -y
        pip install furo nbsphinx sphinx-autodoc-typehints sphinx-copybutton sphinxcontrib-youtube

    # build docs
    - name: Build Sphinx Documentation
      run: "sphinx-build -a -b html docsrc docs"

    # ensure pages configured correctly
    - name: Setup Pages
      uses: actions/configure-pages@v2
      
    # upload docs directory
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload contents of docs directory
        path: "docs"
      
    # deploy automatically to GitHub pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1